// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBuddy.Data;

#nullable disable

namespace TravelBuddy.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260405201948_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBuddy.Models.ChatFile", b =>
                {
                    b.Property<int>("chatid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("chatid"));

                    b.Property<byte[]>("fileData")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("chatid");

                    b.ToTable("ChatFile");
                });

            modelBuilder.Entity("TravelBuddy.Models.Community", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cid"));

                    b.Property<string>("cemail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("cimage")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cpassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("cid");

                    b.HasIndex("cemail");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("TravelBuddy.Models.CommunityChat", b =>
                {
                    b.Property<int>("communityChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("communityChatId"));

                    b.Property<int>("communityId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("usrEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("communityChatId");

                    b.HasIndex("communityId");

                    b.HasIndex("usrEmail");

                    b.ToTable("CommunityChat");
                });

            modelBuilder.Entity("TravelBuddy.Models.Ride", b =>
                {
                    b.Property<int>("rideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("rideId"));

                    b.Property<int?>("communityId")
                        .HasColumnType("int");

                    b.Property<string>("rideEndLatitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rideEndLongitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rideEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("rideGroupLeaderEmail")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("rideStartLatitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rideStartLongitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rideStartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("rideId");

                    b.HasIndex("communityId");

                    b.HasIndex("rideGroupLeaderEmail");

                    b.ToTable("Ride");
                });

            modelBuilder.Entity("TravelBuddy.Models.Usr", b =>
                {
                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("uimage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("email");

                    b.ToTable("Usr");
                });

            modelBuilder.Entity("TravelBuddy.Models.Community", b =>
                {
                    b.HasOne("TravelBuddy.Models.Usr", "usr")
                        .WithMany("communities")
                        .HasForeignKey("cemail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("usr");
                });

            modelBuilder.Entity("TravelBuddy.Models.CommunityChat", b =>
                {
                    b.HasOne("TravelBuddy.Models.Community", "community")
                        .WithMany("communityChats")
                        .HasForeignKey("communityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelBuddy.Models.Usr", "usr")
                        .WithMany("communityChats")
                        .HasForeignKey("usrEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("community");

                    b.Navigation("usr");
                });

            modelBuilder.Entity("TravelBuddy.Models.Ride", b =>
                {
                    b.HasOne("TravelBuddy.Models.Community", "community")
                        .WithMany("rides")
                        .HasForeignKey("communityId");

                    b.HasOne("TravelBuddy.Models.Usr", "usr")
                        .WithMany("rides")
                        .HasForeignKey("rideGroupLeaderEmail");

                    b.Navigation("community");

                    b.Navigation("usr");
                });

            modelBuilder.Entity("TravelBuddy.Models.Community", b =>
                {
                    b.Navigation("communityChats");

                    b.Navigation("rides");
                });

            modelBuilder.Entity("TravelBuddy.Models.Usr", b =>
                {
                    b.Navigation("communities");

                    b.Navigation("communityChats");

                    b.Navigation("rides");
                });
#pragma warning restore 612, 618
        }
    }
}
