// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelBuddy.Data;

#nullable disable

namespace TravelBuddy.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260402080806_M1")]
    partial class M1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelBuddy.Models.Community", b =>
                {
                    b.Property<int>("cid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cid"));

                    b.Property<string>("cemail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("cimage")
                        .HasMaxLength(100)
                        .HasColumnType("varbinary(100)");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("cpassword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("cid");

                    b.HasIndex("cemail");

                    b.ToTable("Community");
                });

            modelBuilder.Entity("TravelBuddy.Models.Usr", b =>
                {
                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("uimage")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("email");

                    b.ToTable("Usr");
                });

            modelBuilder.Entity("TravelBuddy.Models.Community", b =>
                {
                    b.HasOne("TravelBuddy.Models.Usr", "usr")
                        .WithMany("communities")
                        .HasForeignKey("cemail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usr");
                });

            modelBuilder.Entity("TravelBuddy.Models.Usr", b =>
                {
                    b.Navigation("communities");
                });
#pragma warning restore 612, 618
        }
    }
}
